---
name: Schedule - Nightly Acceptance Tests

on:
  schedule:
    - cron: "0 0 * * *"

env:
  LOG_LEVEL: info

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    strategy:
      matrix:
        os:
          - ubuntu
          - debian
          - fedora

    steps:
      - name: Get the current date
        id: date
        run: echo "DATE=$(date +'%d%m%Y')" >> "$GITHUB_ENV"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug Generate Token Parameters
        run: |
          echo "App ID: ${{ secrets.BOT_APP_ID }}"
          echo "Private Key: ${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: lower-repo
        run: echo "repository=${GITHUB_REPOSITORY@L}" >> "$GITHUB_ENV"

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          file: ./tests/${{ matrix.os }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.repository }}:${{ matrix.os }}-${{ env.DATE }}

      - name: Notify about failure
        uses: umahmood/pushover-actions@main
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
        with:
          status: ${{ job.status }}
          title: "🟡 [Dotfiles] - Nightly Build Failed"
          message: "Github Actions Nightly dotfiles build failed. Take a look"
          url_title: "View on Github"
          url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          priority: "-1" # low priority - no sound or vibration generated
        if: failure()
