---
name: lint YAML and Shell

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

env:
  # Currently no way to detect automatically
  DEFAULT_BRANCH: main

jobs:
  build:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@8787d8c41d3302ff274a6bb25cf87470967ee8e1 # v4
        with:
          fetch-depth: 0
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"
      - name: Lint
        uses: super-linter/super-linter@v7
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "${{ env.DEFAULT_BRANCH }}"
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
          MARKDOWN_CONFIG_FILE: .markdownlint.yaml
          YAML_CONFIG_FILE: .yamllint.yaml
          VALIDATE_NATURAL_LANGUAGE: false
