---
name: Schedule/Push - Renovate

on:
  schedule:
    - cron: "*/10 * * * *"
  push:
    branches:
      - main
      - master

env:
  LOG_LEVEL: debug
  DRY_RUN: false
  RENOVATE_CONFIG_FILE: .github/renovate.json5

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Renovate
        uses: renovatebot/github-action@v41.0.13
        with:
          configurationFile: ${{ env.RENOVATE_CONFIG_FILE }}
          token: "x-access-token:${{ steps.generate-token.outputs.token }}"
